### ISSUE TITLE
职业量谱的一些显示问题

### ISSUE THREAD

**Issue by joelyang97** [UTwelve/3AReal#1]
在用插件的时候遇到一个问题。就是能量量谱的显示。
![bug](https://user-images.githubusercontent.com/48947204/61288125-0f7c2400-a7f9-11e9-8119-be4fca070cc0.png)
![bug2](https://user-images.githubusercontent.com/48947204/61288136-13a84180-a7f9-11e9-9ae8-6fbf3a30f133.png)
目前测试了一下，几个现有职业。只发现武僧(50级)和诗人(70级)出现这样的情况。
插件设置如下:
![3](https://user-images.githubusercontent.com/48947204/61288255-523dfc00-a7f9-11e9-9ba4-f4b1644811a3.png)
想请教一下这个问题。是由于什么出现的。怎么解决。

**Comment by UTwelve** [comment]
> 这是由_HackUImask.fx_引起的问题

由于Reshade实现原理的局限性，不能够识别UI的存在，会被作为画面的一部分一起进入后处理环节
_HackUImask.fx_的作用是将UI(界面和菜单)从后处理的流程中隔离开
目的是避免在对画面进行后处理时，对UI产生影响，影响阅读
这是**针对FF14进行设计的**fx，运行在DX11时表现良好
唯一的问题是，在隔离能量量谱时，**某些职业**的能量量谱会被以整个UI块隔离，这应该是游戏制作时疏忽了透明层。

解决办法：可以在游戏的界面设置中，将能量量谱设置为_简洁量普
![_PJJ8~CM(OKTM(4A1UAZE(D](https://user-images.githubusercontent.com/10069011/67579899-f3810a80-f777-11e9-8255-c87bb0d31052.png)
![77S $ X`E}U{}F7}OGWPL3L](https://user-images.githubusercontent.com/10069011/67579900-f419a100-f777-11e9-8551-2044691ca77f.png)

_

**Comment by joelyang97** [comment]
感谢解答。刚看到。
